apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      schedulerName: random-scheduler
      containers:
      - name: sleep
        image: nginx:latest
        imagePullPolicy: IfNotPresent
